DROP PROCEDURE IF EXISTS FILTRO_ANUNCIO;

DELIMITER //

CREATE PROCEDURE FILTRO_ANUNCIO (
  IN IMOVEL    BOOL,
  IN MOVEL     BOOL,
  IN MATERIAL  BOOL,
  IN PETS      BOOL,
  IN MIN_VALOR DOUBLE,
  IN MAX_VALOR DOUBLE,
  IN ORDENACAO INT
)
BEGIN
    DECLARE QUERY_PART1 VARCHAR(5000);
    DECLARE QUERY_PART2 VARCHAR(500);
    DECLARE QUERY_PART3 VARCHAR(8000);
    DECLARE QUERY_FINAL VARCHAR(8000);
    -- INICIALIZA AS VARIAVEIS PORQUE NÃO SE PODE CONCATENAR COM VALORES NULL
    SET QUERY_FINAL = '';
    SET QUERY_PART3 = '';
    
    -- TRATAMENTO DE DADOS DOS PARAMETROS DE ENTRADA
    SET IMOVEL    = COALESCE(IMOVEL, FALSE);
    SET MOVEL     = COALESCE(MOVEL, FALSE);
    SET MATERIAL  = COALESCE(MATERIAL, FALSE);
    SET PETS      = COALESCE(PETS, FALSE);
    SET MIN_VALOR = COALESCE(MIN_VALOR, 0.0);
    SET MAX_VALOR = COALESCE(MAX_VALOR, 100000000.00);
    SET ORDENACAO = COALESCE(ORDENACAO, 0);
    
    SET QUERY_PART1 = 'SELECT\n
                        ID_ANUNCIO,\n
                        DS_TITULO,\n
                        ANUNCIO.DS_DESCRICAO      AS DS_ANUNCIO,\n
                        NR_VALOR,\n
                        TB_CATEGORIA_ID_CATEGORIA AS ID_CATEGORIA,\n
                        CAT_ANUNCIO.DS_DESCRICAO  AS DS_CATEGORIA,\n
                        FOTO.DS_CAMINHO           AS DS_CAMINHO,\n
                        IMOVEL.NR_PET             AS PETS\n
                      FROM\n
                        TB_ANUNCIO AS ANUNCIO\n
                        LEFT JOIN\n
                          TB_CATEGORIA_ANUNCIO AS CAT_ANUNCIO ON CAT_ANUNCIO.ID_CATEGORIA = ANUNCIO.TB_CATEGORIA_ID_CATEGORIA\n
                        LEFT JOIN\n
                          TB_FOTOS AS FOTO ON FOTO.TB_ANUNCIO_ID_ANUNCIO = ANUNCIO.ID_ANUNCIO\n
                        LEFT JOIN\n
                          TB_IMOVEL AS IMOVEL ON IMOVEL.ID_IMOVEL = ANUNCIO.TB_IMOVEL_idTB_IMOVEL\n
                      WHERE\n
                        TB_STATUS_ID_STATUS = 2\n';
                        
    SET QUERY_PART2 = '\nGROUP BY\n
                        ANUNCIO.ID_ANUNCIO\n
                      ORDER BY\n';
    
    -- ADICIONA O PARAMETRO DO VALOR DO ANUNCIO
    SET QUERY_PART1 = CONCAT(QUERY_PART1, 'AND ANUNCIO.NR_VALOR BETWEEN ', MIN_VALOR, ' AND ', MAX_VALOR, ' \n');

    IF IMOVEL = TRUE AND MOVEL = TRUE AND MATERIAL = TRUE THEN
      SET QUERY_PART3 = CONCAT(QUERY_PART1, '\nAND ANUNCIO.TB_CATEGORIA_ID_CATEGORIA IN (1, 2, 3)\n');
    ELSEIF IMOVEL = TRUE AND MOVEL = TRUE THEN
      SET QUERY_PART3 = CONCAT(QUERY_PART1, '\nAND ANUNCIO.TB_CATEGORIA_ID_CATEGORIA IN (1, 2)\n');
    ELSEIF IMOVEL = TRUE AND MATERIAL = TRUE THEN
      SET QUERY_PART3 = CONCAT(QUERY_PART1, '\nAND ANUNCIO.TB_CATEGORIA_ID_CATEGORIA IN (1, 3)\n');
    ELSEIF MOVEL = TRUE AND MATERIAL = TRUE THEN
      SET QUERY_PART3 = CONCAT(QUERY_PART1, '\nAND ANUNCIO.TB_CATEGORIA_ID_CATEGORIA IN (2, 3)\n');
    ELSEIF IMOVEL = TRUE THEN
      SET QUERY_PART3 = CONCAT(QUERY_PART1, '\nAND ANUNCIO.TB_CATEGORIA_ID_CATEGORIA = 1\n');
    ELSEIF MOVEL = TRUE THEN
      SET QUERY_PART3 = CONCAT(QUERY_PART1, '\nAND ANUNCIO.TB_CATEGORIA_ID_CATEGORIA = 2\n');
    ELSEIF MATERIAL = TRUE THEN
      SET QUERY_PART3 = CONCAT(QUERY_PART1, '\nAND ANUNCIO.TB_CATEGORIA_ID_CATEGORIA = 3\n');
    END IF;
    
    -- VERIFICA SE É IMOVEL E SE PERMITE PETS
    IF IMOVEL = TRUE AND PETS = TRUE THEN
      SET QUERY_PART3 = CONCAT(QUERY_PART1, '\nAND IMOVEL.NR_PET = 1\n');
    END IF;
    
    -- VALIDA SE PASSADO ALGUM PARAMETRO EM IMOVEL, MOVEL, MATERIAL
    IF QUERY_PART3 = '' THEN
      SET QUERY_FINAL = CONCAT(QUERY_PART1, QUERY_PART2);
    ELSE
      SET QUERY_FINAL = CONCAT(QUERY_PART3, QUERY_PART2);
    END IF;
    
    -- DEFINE A ORDENAÇÃO DO RESULT SET
    IF ORDENACAO = 0 THEN
      SET QUERY_FINAL = CONCAT(QUERY_FINAL, 'ID_ANUNCIO ASC');
    ELSEIF ORDENACAO = 1 THEN
      SET QUERY_FINAL = CONCAT(QUERY_FINAL, 'NR_VALOR ASC');
    ELSEIF ORDENACAO = 2 THEN
      SET QUERY_FINAL = CONCAT(QUERY_FINAL, 'NR_VALOR DESC');
    ELSEIF ORDENACAO = 3 THEN
      SET QUERY_FINAL = CONCAT(QUERY_FINAL, 'DS_TITULO ASC');
    END IF;
    
    SET @Query = QUERY_FINAL;
    
    PREPARE CMD FROM @Query;
    
    EXECUTE CMD;

END //

DELIMITER ;