DROP PROCEDURE IF EXISTS MANUTENCAO_PREFERENCIAS

DELIMITER //

CREATE PROCEDURE MANUTENCAO_PREFERENCIAS (
  IN ID_USUARIO         INT,
  IN PREF_IMOVEL        INT,
  IN PREF_CAT_IMOVEL    INT,
  IN PREF_MATERIAL      INT,
  IN PREF_CAT_MATERIAL  INT,
  IN PREF_MOVEL         INT,
  IN PREF_CAT_MOVEL     INT,
  IN PREF_PETS          INT,
  IN PREF_MORAR_SOZINHO INT
)
BEGIN
  IF EXISTS (SELECT 1 FROM TB_PREFERENCIAS WHERE TB_PREFERENCIAS.ID_USUARIO = ID_USUARIO) THEN
    UPDATE TB_PREFERENCIAS SET
      TB_PREFERENCIAS.ID_USUARIO         = IFNULL(ID_USUARIO, TB_PREFERENCIAS.ID_USUARIO),
      TB_PREFERENCIAS.PREF_IMOVEL        = IFNULL(PREF_IMOVEL, TB_PREFERENCIAS.PREF_IMOVEL),
      TB_PREFERENCIAS.PREF_CAT_IMOVEL    = IFNULL(PREF_CAT_IMOVEL, TB_PREFERENCIAS.PREF_CAT_IMOVEL),
      TB_PREFERENCIAS.PREF_MATERIAL      = IFNULL(PREF_MATERIAL, TB_PREFERENCIAS.PREF_MATERIAL),
      TB_PREFERENCIAS.PREF_CAT_MATERIAL  = IFNULL(PREF_CAT_MATERIAL, TB_PREFERENCIAS.PREF_CAT_MATERIAL),
      TB_PREFERENCIAS.PREF_MOVEL         = IFNULL(PREF_MOVEL, TB_PREFERENCIAS.PREF_CAT_MOVEL),
      TB_PREFERENCIAS.PETS               = IFNULL(PETS, TB_PREFERENCIAS.PETS),
      TB_PREFERENCIAS.PREF_MORAR_SOZINHO = IFNULL(PREF_MORAR_SOZINHO, TB_PREFERENCIAS.PREF_MORAR_SOZINHO)
    WHERE
      TB_PREFERENCIAS.ID_USUARIO = ID_USUARIO;
  ELSE
    INSERT INTO TB_PREFERENCIAS (
      ID_USUARIO        ,
      PREF_IMOVEL       ,
      PREF_CAT_IMOVEL   ,
      PREF_MATERIAL     ,
      PREF_CAT_MATERIAL ,
      PREF_MOVEL        ,
      PREF_CAT_MOVEL    ,
      PREF_PETS         ,
      PREF_MORAR_SOZINHO
    ) VALUES (
      ID_USUARIO        ,
      PREF_IMOVEL       ,
      PREF_CAT_IMOVEL   ,
      PREF_MATERIAL     ,
      PREF_CAT_MATERIAL ,
      PREF_MOVEL        ,
      PREF_CAT_MOVEL    ,
      PREF_PETS         ,
      PREF_MORAR_SOZINHO
    );
  END IF;

END //

DELIMITER ;